ok i think we're making progress. got up to 14 tqdm progress bars. I think the error might have been as simple as a - instead of a _ charater in the directory path.
current error message is:

FileNotFoundError: [Errno 2] No such file or directory: 'curious_oath/model_5.bin'

its not fixed, but its progress